name: Build JPX APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show root files
        run: |
          pwd
          ls -la

      - name: Fix gradlew permission
        run: |
          chmod 777 gradlew
          ls -l gradlew

      - name: Fix line endings (CRLF issue)
        run: sed -i 's/\r$//' gradlew

      - name: Verify gradlew
        run: bash gradlew --version

      - name: Build APK
        run: bash gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: jpx-apk
          path: app/build/outputs/apk/debug/app-debug.apk    
